### ISSUE TITLE
装载全饰品无法启动

### ISSUE THREAD

**Issue by Xcating** [CubeWhyMC/LunarUC#1]
装在 
![image](https://github.com/CubeWhyMC/LunarUC/assets/82816129/23250d11-13ce-4b1a-b2de-543135a552a1)
LunarUC-1.0-SNAPSHOT-fatjar.jar后无法启动，其他javaagents均可使用
![image](https://github.com/CubeWhyMC/LunarUC/assets/82816129/7ed9e881-12d8-4da3-aa27-686016daf17b)
日志好像也没说明什么，反正就是不能用就对了 :)

**Comment by Xcating** [comment]
[latest.log](https://github.com/CubeWhyMC/LunarUC/files/12241792/latest.log)
日志文件

**Comment by Xcating** [comment]
![ff50f77edd2ff7b5981ec917260845da](https://github.com/CubeWhyMC/LunarUC/assets/82816129/116ac2c5-9a9b-4f73-b68f-9d61877be3f6)
有人好像又能用 :)

**Comment by cubewhy** [comment]
kotlin存在问题，已修复
